### ISSUE TITLE
Fix SQL injection vulnerability

### ISSUE THREAD

**Issue by bschlief** [stepheno/brewtronic-5000#15]
Looks like /config/initializers/secret_token.rb probably shouldn't be hosted on the github.  Also need to update rails.

See the following:
https://threatpost.com/en_us/blogs/sql-injection-flaw-haunts-all-ruby-rails-versions-010313
http://weblog.rubyonrails.org/2013/1/2/Rails-3-2-10--3-1-9--and-3-0-18-have-been-released/

**Comment by stepheno** [comment]
Yeah, i saw that. We aren't vulnerable, as we aren't using the method that
allows injection. But we should upgrade rails anyways.
